### PR TITLE
add linux/falloc.h headers so the fallocate_{basic,align,stress}.c te…

### PR DESCRIPTION
**Pull request by npe9**
…sts don't fail

### CODE REVIEW

**Comment by npe9** [comment]
Was this fixed or was I doing something wrong? We're currently using my personal version, we'd like to use the mainline.

**Comment by khers** [comment]
It was merged into next and will be put into the next release.  Also, all code is taken via the mailing list not pull requests.

**Comment by npe9** [comment]
Gotcha, I've had trouble signing up to the mailing list (send a mail, have a response sent, accept response be on the list). Is there anyone I can talk to about troubleshooting?

**Comment by khers** [comment]
So we moved the mailing list from librelist (which is broken) to Google groups.  The current mailing list is libhugetlbfs@googlegroups.com

Eric

**Comment by npe9** [comment]
That's what I was missing. Thanks!

**Pull request closed without merging**
